---

# project name, derived from parent folder, e.g. dvang
project_name: "{{ playbook_dir | dirname | basename }}"

# host name where site will be served, e.g. dvang.local
host_name: "{{ project_name }}.local"

# linux user who will own project files
user_name: "{{ ansible_user }}"

# home path for project and virtualenv, e.g. /home/ubuntu
home_path: /home/{{ user_name }}

# project path, e.g. /home/ubuntu/project
project_path: "{{ home_path }}/{{ project_name }}"

# public path, e.g. /home/ubuntu/project/public
public_path: "{{ project_path }}/public"

# database config
db_name: "{{ project_name }}"
db_user: "{{ project_name }}"
db_pass: "{{ project_name }}"
db_host: localhost
