---

# project name
project_name: dvang

# host name where site will be served
host_name: dvang.local

# linux user who will own project files
user_name: "{{ ansible_user }}"

# home path for project and virtualenv, e.g. /home/ubuntu
home_path: /home/{{ user_name }}

# project path, e.g. /home/ubuntu/project
project_path: "{{ home_path }}/{{ project_name }}"

# public path, e.g. /home/ubuntu/project/public
public_path: "{{ project_path }}/public"

# database config
db_name: "{{ project_name }}"
db_user: "{{ project_name }}"
db_pass: "{{ project_name }}"

