---

- name: Playbook for production
  hosts: all
  become: yes
  vars:
    project_name: dvang
    host_name: dvang.party
    django_migrate: false
    django_load_fixtures: false
    django_collectstatic: true
    gunicorn_autostart: true
    gunicorn_enabled: true
    nginx_use_ssl: true
    nginx_enabled: true

  roles:
    - project
